---
root: true

# parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  # - plugin:@typescript-eslint/eslint-recommended
  # - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jest/recommended
  - airbnb
  - prettier
  # - prettier/@typescript-eslint

plugins:
  - import
  - jest
  - prettier
  # - '@typescript-eslint'
  - unused-imports

settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']

env:
  es6: true
  browser: true
  node: true
  jasmine: true
  jest: true
  jest/globals: true

rules:
  # '@typescript-eslint/member-delimiter-style': off
  # '@typescript-eslint/no-explicit-any': off
  import/extensions: off
  no-shadow: 0
  no-unused-vars: 0
  prefer-destructuring: 0
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-imports-ts: error
  unused-imports/no-unused-vars: error
  unused-imports/no-unused-vars-ts: error
