---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: ['./tsconfig.json']
  ecmaVersion: 2021

extends:
  # - airbnb-base
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:chai-friendly/recommended
  - plugin:import/errors
  - plugin:import/typescript
  - plugin:import/warnings
  - plugin:prettier/recommended
  # - prettier/@typescript-eslint

plugins:
  - import
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: ['.ts']
      paths: [src]
    typescript: {}

env:
  es6: true
  mocha: true
  node: true

rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-use-before-define': ['error']
  # this next line is disabling all the warnings about non typed stuff:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-floating-promises': off
  comma-dangle: [error, only-multiline]
  curly: [error, multi-or-nest]
  eol-last: ['error', 'always']
  func-names: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  no-console: off
  no-debugger: warn
  no-fallthrough: warn
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor: [memo]
  no-shadow: warn
  no-unused-vars: warn
  no-use-before-define: off
  object-shorthand: error
  prefer-destructuring: warn
  prefer-template: error
