env:
  # es6: true
  mocha: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
globals: {}
parserOptions:
  ecmaVersion: 2019
rules:
  no-unused-vars:
    - error
    - args: none
