---
root: true

parserOptions:
  project: ['./tsconfig.json']
  ecmaVersion: 2021

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - airbnb-base
  - plugin:prettier/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:chai-friendly/recommended

plugins:
  - import
  - prettier
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: ['.ts']

env:
  es6: true
  mocha: true
  node: true

rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-use-before-define': ['error']
  # this next line is disabling all the warnings about non typed stuff:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-floating-promises': off
  func-names: 'off'
  import/no-extraneous-dependencies: off
  import/extensions: off
  eol-last: ['error', 'always']
  no-shadow: warn
  no-unused-vars: warn
  prefer-destructuring: warn
  no-use-before-define: 'off'
  no-console: 'off'
  object-shorthand: error
  no-debugger: error
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor: [memo]
