---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: [./tsconfig.json]
  ecmaVersion: 2021

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:prettier/recommended
  - prettier

plugins:
  - import
  - unused-imports
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: [.ts]
      paths: [src]
    typescript: {}

env:
  es6: true
  node: true

rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/explicit-function-return-type': off
  # this next line is disabling all the warnings about non typed stuff:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-shadow':
    - error
    - allow:
        - deps
        - secrets
        - values
  '@typescript-eslint/no-unsafe-argument': warn
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-unused-vars': [warn, { argsIgnorePattern: ^(_|next), varsIgnorePattern: ^_ }]
  '@typescript-eslint/no-use-before-define': ['error']
  '@typescript-eslint/restrict-template-expressions': off
  comma-dangle: [error, only-multiline]
  curly: [error, multi-or-nest]
  eol-last: ['error', 'always']
  func-names: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  no-console: off
  no-debugger: warn
  no-fallthrough: warn
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor: [memo]
  no-shadow: off
  no-unused-vars: off
  no-use-before-define: off
  object-shorthand: error
  prefer-destructuring: warn
  prefer-template: error
  unused-imports/no-unused-imports-ts: error
