swagger: '2.0'
host: otomi-stack-api
basePath: /v1
info:
  title: The otomi-stack API
  version: '1.0.0'
definitions:
  Error:
    additionalProperties: true
  Team:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
  Teams:
    properties:
      teams: 
        type: array
        items: 
          $ref: '#/definitions/Team'

paths:
  /teams:
    get:
      description: Get teams collection
      operationId: getTeams
      parameters: []
      responses:
        200:
          description: Successfully obtained teams collection
          schema:
            $ref: '#/definitions/Teams'
  /apiDocs:
    get:
      operationId: getApiDoc
      description: Returns the requested apiDoc
      parameters:
        - description: The type of apiDoc to return.
          in: query
          name: type
          type: string
          enum:
            - apiDoc
            - operationDoc
      responses:
        200:
          description: The requested apiDoc.
          schema:
            type: object
        default:
          description: The requested apiDoc.

