version: '3.4'

services:
  api:
    container_name: api
    build:
      context: .
      target: dev
      args:
        - NPM_TOKEN
    image: eu.gcr.io/otomi-cloud/otomi-api:${API_TAG:-dev}
    user: ${USER_ID}:${GROUP_ID}
    command: sh -c 'rm -rf /tmp/otomi-stack && npm run dev:docker'
    ports:
      - 8080:8080

    volumes:
      - ./:/app
      - ./test/core.yaml:/etc/otomi/core.yaml
      - /tmp:/tmp:rw
    working_dir: /app
    environment:
      TOOLS_HOST: tools
      HOME: /app
