version: '3.4'

services:
  tools:
    container_name: tools
    image: eu.gcr.io/otomi-cloud/otomi-stack:${TOOLS_TAG:-latest}
    user: ${USER_ID}
    command: bin/server.sh
    expose:
      - 17771
    ports:
      - 17771:17771
    volumes:
      - /tmp:/tmp:rw
    environment:
      ENV_DIR: ${GIT_LOCAL_PATH}
      GCLOUD_SERVICE_KEY: ${GCLOUD_SERVICE_KEY}
