version: '3.4'

services:
  tools:
    container_name: tools
    image: otomi/core:${TOOLS_TAG:-main}
    user: ${USER_ID}
    command: binzx/otomi server
    expose:
      - 17771
    ports:
      - 17771:17771
    volumes:
      - $ENV_DIR:$ENV_DIR
    environment:
      ENV_DIR: $ENV_DIR
      VERBOSITY: 2
    env_file:
      - .env
