version: '3.4'

services:
  tools:
    container_name: tools
    image: otomi/core:${TOOLS_TAG:-master}
    user: ${USER_ID}
    command: bin/server.sh
    expose:
      - 17771
    ports:
      - 17771:17771
    volumes:
      - /tmp:/tmp
    environment:
      ENV_DIR: /tmp/otomi-values
    env_file:
      - .env
