apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tty-$EMAIL
  name: tty-$EMAIL
  namespace: team-admin
spec:
  serviceAccountName: tty-$EMAIL
  volumes:
    - name: kconfig
      configMap:
        name: kconfig
  containers:
    - image: otomi/tty:0.1.1
      name: po
      resources:
        requests:
          memory: '128Mi'
          cpu: '250m'
        limits:
          memory: '256Mi'
          cpu: '500m'
      volumeMounts:
        - name: kconfig
          mountPath: /etc/kconfig
      command:
        - su
        - '-'
        - user
        - -c
        - sh /etc/kconfig/kconfig.sh && ttyd -w /home/user -u 1000 -g 1000 -p 8080 sh
---

