apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tty-$EMAIL
  name: tty-$EMAIL
  namespace: team-admin
spec:
  serviceAccountName: tty-$EMAIL
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  volumes:
    - name: kconfig
      configMap:
        name: kconfig-team-$TARGET_TEAM
  containers:
    - image: otomi/tty:1.0.0
      name: po
      resources:
        requests:
          memory: '128Mi'
          cpu: '250m'
        limits:
          memory: '256Mi'
          cpu: '500m'
      volumeMounts:
        - name: kconfig
          mountPath: /etc/kconfig
      command:
        - bash
        - -c
        - bash /etc/kconfig/kconfig.sh && ttyd -w /home/user -p 8080 tmux new -A
---

