apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tty-$SUB
  namespace: team-admin
spec:
  gateways:
    - team-admin/team-admin-public-tlsterm
  hosts:
    - tty.$FQDN
  http:
    - match:
        - uri:
            prefix: /platform-logout
      redirect:
        authority: auth.$FQDN
        uri: /oauth2/sign_out?rd=https%3A%2F%2Fkeycloak.$FQDN%2Frealms%2Fotomi%2Fprotocol%2Fopenid-connect%2Flogout%3Fpost_logout_redirect_uri%3Dhttps%3A%2F%2Fconsole.$FQDN%26client_id%3Dotomi
        redirectCode: 302
    - match:
        - uri:
            prefix: /$SUB
      rewrite:
        uri: /
      route:
        - destination:
            host: tty-$SUB.team-admin.svc.cluster.local
            port:
              number: 8080
          headers:
            request:
              set:
                X-Forwarded-Proto: https
---

