AppAlertmanager:
  additionalProperties: false
  x-externalDocsPath: https://prometheus.io/docs/alerting/latest/alertmanager/
  x-short: Alerting made easy
  description: The Alertmanager handles alerts sent by client applications such as the Prometheus server. It takes care of deduplicating, grouping, and routing them to the correct receiver integration such as email, PagerDuty, or OpsGenie. It also takes care of silencing and inhibition of alerts.
  title: Alertmanager
  type: object
  properties:
    id:
      $ref: ../definitions.yaml#/idName
    enabled:
      type: boolean
      default: false
    rawValues:
      $ref: ../definitions.yaml#/rawValues
    shortcuts:
      description: Resource URL that lands the user in a place of interest within an app.
      type: array
      nullable: true
      items:
        $ref: ../definitions.yaml#/shortcut
    values:
      additionalProperties: false
      type: object
      properties:
        image:
          $ref: ../definitions.yaml#/image
        resources:
          $ref: ../definitions.yaml#/resources
