AppPrometheus:
  additionalProperties: false
  type: object
  properties:
    id:
      $ref: ../definitions.yaml#/idName
    enabled:
      type: boolean
      default: false
    rawValues:
      $ref: ../definitions.yaml#/rawValues
    shortcuts:
      description: Resource URL that lands the user in a place of interest within an app.
      type: array
      nullable: true
      items:
        $ref: ../definitions.yaml#/shortcut
    values:
      x-externalDocsPath: docs/apps/prometheus
      additionalProperties: false
      type: object
      properties:
        role:
          $ref: ../definitions.yaml#/prometheusRole
        replicas:
          $ref: ../definitions.yaml#/replicas
        scrapeInterval:
          $ref: ../definitions.yaml#/duration
          default: 60s
        retention:
          $ref: ../definitions.yaml#/duration
        retentionSize:
          type: string
          description: 'The maximum number of bytes of storage blocks to retain. The oldest data will be removed first. Defaults to 0 or disabled. Units supported: B, KB, MB, GB, TB, PB, EB'
          default: 4GB
          pattern: '^([0-9]+\.)?[0-9]+(B|KB|MB|GB|TB|PB|EB)?$'
        storageSize:
          $ref: ../definitions.yaml#/size
          default: 5Gi
        # image:
        #   type: object
        #   properties:
        #     prometheus:
        #       type: object
        #       properties:
        #         tag:
        #           $ref: ../definitions.yaml#/imageTag
        #           default: v2.30.3
        #         pullPolicy:
        #           $ref: ../definitions.yaml#/imagePullPolicy
        #     kube-state-metrics:
        #       type: object
        #       properties:
        #         tag:
        #           $ref: ../definitions.yaml#/imageTag
        #           default: v1.8.0
        #         pullPolicy:
        #           $ref: ../definitions.yaml#/imagePullPolicy
        #     node-exporter:
        #       type: object
        #       properties:
        #         tag:
        #           $ref: ../definitions.yaml#/imageTag
        #           default: v1.3.1
        #         pullPolicy:
        #           $ref: ../definitions.yaml#/imagePullPolicy
        resources:
          type: object
          properties:
            prometheus:
              type: object
              properties:
                limits:
                  type: object
                  properties:
                    cpu:
                      $ref: ../definitions.yaml#/quantityCpu
                      default: 500m
                    memory:
                      $ref: ../definitions.yaml#/quantityMem
                      default: 256Mi
                requests:
                  type: object
                  properties:
                    cpu:
                      $ref: ../definitions.yaml#/quantityCpu
                      default: 100m
                    memory:
                      $ref: ../definitions.yaml#/quantityMem
                      default: 128Mi
              required:
                - limits
                - requests
            kube-state-metrics:
              type: object
              properties:
                limits:
                  type: object
                  properties:
                    cpu:
                      $ref: ../definitions.yaml#/quantityCpu
                      default: 100m
                    memory:
                      $ref: ../definitions.yaml#/quantityMem
                      default: 256Mi
                requests:
                  type: object
                  properties:
                    cpu:
                      $ref: ../definitions.yaml#/quantityCpu
                      default: 100m
                    memory:
                      $ref: ../definitions.yaml#/quantityMem
                      default: 128Mi
              required:
                - limits
                - requests
            node-exporter:
              type: object
              properties:
                limits:
                  type: object
                  properties:
                    cpu:
                      $ref: ../definitions.yaml#/quantityCpu
                      default: 500m
                    memory:
                      $ref: ../definitions.yaml#/quantityMem
                      default: 128Mi
                requests:
                  type: object
                  properties:
                    cpu:
                      $ref: ../definitions.yaml#/quantityCpu
                      default: 100m
                    memory:
                      $ref: ../definitions.yaml#/quantityMem
                      default: 128Mi
              required:
                - limits
                - requests
