openapi: 3.0.0
security:
  - groupAuthz: []
info:
  title: The otomi-stack API
  version: 0.1.0
# the x- prefix allows to define own objects that are ignored by openapi spec validation
x-fields:
  domain: &domainNameField
    type: string
    pattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
  repository: &repositoryField
    type: string
    pattern: ^[a-z0-9]+(?:[/._-]{1,2}[a-z0-9]+)*$
    description: A container image repository
  memoryQuantity: &k8sResourceMemoryQuantityField
    type: string
    pattern: ^[0-9]+\.?[0-9]+(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)?$
  cpuQuantity: &k8sResourceCpuQuantityField
    type: string
    pattern: ^([0-9]+\.[0-9]{1,2})|([0-9]{2,3}m)?$
  env: &envField
    type: string
    pattern: ^[A-Z0-9_]*$
  annotation: &k8sAnnotationField
    type: string
    pattern: ^((.){1,253}\/)?(.){1,63}$

paths:
  /readiness:
    get:
      security: []
      description: Check readiness
      responses:
        "200":
          description: Service is ready
  /teams:
    get:
      operationId: getTeamCollection
      description: Get teams collection
      responses:
        "200":
          description: Successfully obtained teams collection
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Teams"
    post:
      operationId: createTeam
      description: Create a team
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Team"
        description: Team object that needs to be added to the collection
        required: true
      responses:
        "200":
          description: Successfully obtained teams collection
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Team"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
        "409":
          description: Team already exists
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
  "/teams/{teamId}":
    get:
      operationId: getTeam
      description: Get a specific team
      parameters:
        - name: teamId
          in: path
          description: ID of team to return
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully obtained team
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Team"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
        "404":
          description: Team does not exists
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
    put:
      operationId: editTeam
      description: Edit a team
      parameters:
        - name: teamId
          in: path
          description: ID of team to return
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Team"
        description: Team object that contains updated values
        required: true
      responses:
        "200":
          description: Successfully edited team
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Team"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
        "404":
          description: Team does not exists
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
    delete:
      operationId: deleteTeam
      description: Delete team
      parameters:
        - name: teamId
          in: path
          description: ID of team to delete
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully deleted a team
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
        "404":
          description: Team does not exists
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
  "/teams/{teamId}/services":
    get:
      operationId: getServiceCollectionFromTeam
      description: Get services from a given team
      parameters:
        - name: teamId
          in: path
          description: ID of team
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully obtained services
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Services"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
    post:
      operationId: addServiceToTeam
      description: Create a service
      parameters:
        - name: teamId
          in: path
          description: ID of team
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Service"
        description: Service object
        required: true
      responses:
        "200":
          description: Successfully stored service configuration
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Service"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
        "409":
          description: Team already exists
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
  "/teams/{teamId}/services/{serviceId}":
    get:
      operationId: getServiceFromTeam
      description: Get a service from a given team
      parameters:
        - name: teamId
          in: path
          description: ID of team to return
          required: true
          schema:
            type: string
        - name: serviceId
          in: path
          description: ID of the service
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully obtained service configuration
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Service"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
        "404":
          description: Service does not exists
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
    put:
      operationId: editServiceFromTeam
      description: Edit a service from a given team
      parameters:
        - name: teamId
          in: path
          description: ID of team to return
          required: true
          schema:
            type: string
        - name: serviceId
          in: path
          description: ID of the service
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Service"
        description: Service object that contains updated values
        required: true
      responses:
        "200":
          description: Successfully edited service
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Team"
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
        "404":
          description: Service does not exists
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
    delete:
      operationId: deleteServiceFromTeam
      description: Delete a service from a given team
      parameters:
        - name: teamId
          in: path
          description: ID of team to delete
          required: true
          schema:
            type: string
        - name: serviceId
          in: path
          description: ID of the service
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully deleted a service
        "400":
          description: Bad Request
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OpenApiValidationError"
        "404":
          description: Service does not exists
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
  /deployments:
    post:
      operationId: deploy
      description: Trigger a deployment (only for admin)
      responses:
        "202":
          description: Deployment has been triggered
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Deployment"
        "409":
          description: Unable not push data to git repo
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/OtomiStackError"
  /apiDocs:
    get:
      security: []
      description: Get OpenApi document
      responses:
        "200":
          description: The requested apiDoc.
          content:
            "application/json":
              schema:
                type: object
        default:
          description: The requested apiDoc.
servers:
  - url: "/v1"

# -------------------- Components
components:
  securitySchemes:
    groupAuthz:
      type: apiKey
      name: Auth-Group
      in: header
  schemas:
    KubernetesService: &KubernetesService
      type: object
      properties:
        name:
          type: string
          description: A name of existing kubernetes service

    KnativeService: &KnativeService
      # description: Knative service definition
      type: object
      properties:
        repository:
          <<: *repositoryField
        tag:
          type: string
        env:
          description: Environment variables for containers
          type: array
          items:
            type: object
            properties:
              name:
                <<: *envField
              value:
                type: string
                maxLength: 131072
            required:
              - name
              - value
        resources:
          description: Compute resources for containers
          type: object
          properties:
            requests:
              type: object
              properties:
                cpu:
                  <<: *k8sResourceCpuQuantityField
                  default: 50m
                memory:
                  <<: *k8sResourceMemoryQuantityField
                  default: 64Mi
              required:
                - cpu
                - memory
            limits:
              type: object
              properties:
                cpu:
                  <<: *k8sResourceCpuQuantityField
                  default: 100m
                memory:
                  <<: *k8sResourceMemoryQuantityField
                  default: 128Mi
              required:
                - cpu
                - memory
        annotations:
          description: Kubernetes annotations with arbitrary metadata
          type: array
          items:
            type: object
            properties:
              name:
                <<: *k8sAnnotationField
              value:
                type: string
                maxLength: 32767
            required:
              - name
              - value
      required:
        - repository
        - tag
    Deployment:
      properties:
        id:
          type: integer
        status:
          type: string
          readOnly: true
          description: Deployment status
          enum:
            - in-progress
            - completed
            - failed
    Team:
      properties:
        name:
          type: string
          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
          example: "team-1"
          description: A team name
        password:
          type: string
          example: "strongpasswprd"
          writeOnly: true
        # oidc:
        #   $ref: "#/components/schemas/TeamOidc"
        teamId:
          type: string
          readOnly: true
        # slackUrl:
        #   type: string
        #   pattern: ^(https?):\/\/[^\s$.?#].[^\s]*$
        #   example: https://hooks.slack.com/services/service-01
        # resourceQuota:
        #   type: object
      required:
        - name
        - password
        # - oidc
    TeamOidc:
      properties:
        clientID:
          type: string
          example: "ad8611c4-a701-4ec8-8ad3-a510441e728f"
        clientSecret:
          type: string
          example: "Qn/=aZ7x]b/8PgGJhbtAlAejq0fA0P1K"
      required:
        - clientID
        - clientSecret
    Teams:
      properties:
        teams:
          type: array
          items:
            $ref: "#/components/schemas/Team"
    Services:
      properties:
        services:
          type: array
          items:
            $ref: "#/components/schemas/Service"
    Service:
      properties:
        name:
          type: string
          description: A unique subdomain
          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
          example: service-01
        domain:
          type: string
          description: A custom domain
          <<: *domainNameField
          example: redkubes.com
        # svc:
        #   <<: *KubernetesService
        # ksvc:
        #   <<: *KnativeService
        serviceType:
          type: object
          anyOf:
          - type: object
            title: "Knative service"
            properties:
              ksvc:
                <<: *KnativeService
          - type: object
            title: "Kubernetes service"
            properties:
              svc:
                <<: *KubernetesService
        teamId:
          type: string
          readOnly: true
        serviceId:
          type: string
          readOnly: true
        hasCert:
          type: boolean
          default: false
          # description: If true certificate is generated automatically. Otherwise it is expected that administrator provides cert as a secret 'cert-team-$teamName-$serviceName' for a given team.
        certArn:
          type: string
          description: Only if hasCert set to true and deployed on AWS
          example: arn:aws:acm:eu-central-1:xxx:certificate/xxx
      required:
        - name
    OpenApiValidationError:
      properties:
        status:
          type: integer
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"
    ValidationError:
      properties:
        path:
          type: string
        errorCode:
          type: string
        message:
          type: string
        location:
          type: string
          enum:
            - body
            - path
    OtomiStackError:
      properties:
        message:
          type: string
