import { str, bool, json } from 'envalid'
export { cleanEnv } from 'envalid'

export const GIT_REPO_URL = str({ desc: 'The git repo url' })
export const GIT_LOCAL_PATH = str({ desc: 'The local file path to the repo', default: '/tmp/otomi-stack' })
export const GIT_BRANCH = str({ desc: 'The git repo branch', default: 'master' })
export const GIT_USER = str({ desc: 'The git username' })
export const GIT_PASSWORD = str({ desc: 'The git password' })
export const GIT_EMAIL = str({ desc: 'The git user email' })
export const DB_PATH = str({ desc: 'The file path to the db. If not given in-memory db is used.', default: undefined })
export const CLUSTER_ID = str({ desc: 'The cluster id', default: 'google/dev' })
export const CLUSTER_NAME = str({ desc: 'The cluster name' })
export const CLUSTER_APISERVER = str({ desc: 'The cluster api server ip/host' })
export const DISABLE_SYNC = bool({ desc: 'Wether to disable pushing to the repo', default: false })
export const TENANT_ID = str({ desc: 'A Cloud Tenant ID' })
export const TENANT_CLIENT_ID = str({ desc: 'A Cloud Application ID' })
export const TENANT_CLIENT_SECRET = str({ desc: 'A Cloud Application Secret' })
export const IDP_ALIAS = str({ desc: 'A name for the Identity Provider Entry' })
export const REDIRECT_URIS = json({ desc: "A list of Redirect URI's in JSON format" })
export const IDP_GROUP_OTOMI_ADMIN = str({ desc: 'Otomi Admin IDP Group ID' })
export const IDP_GROUP_MAPPINGS_TEAMS = json({ desc: "A list of Team Names and Group Id's from the IDP" })
export const IDP_OIDC_URL = str({ desc: "The Provider's OIDC enpoints url" })
export const KEYCLOAK_ADMIN = str({ desc: 'Default Admin User for KeyCloak Server' })
export const KEYCLOAK_ADMIN_PASSWORD = str({ desc: 'Default Password for Admins' })
export const KEYCLOAK_ADDRESS = str({ desc: 'Default Keycloak Server Address' })
export const KEYCLOAK_CLIENT_SECRET = str({ desc: 'A Keycloak Client Application Secret' })
export const KEYCLOAK_REALM = str({ desc: 'Default Keycloak Realm' })
export const TOOLS_HOST = str({ desc: 'The host of the tools server', default: '127.0.0.1' })
