#!/bin/sh

# configure/install nvm
source_nvm() {
  if [ -f ~/.nvm/nvm.sh ]; then
    echo 'Sourcing nvm from ~/.nvm'
    . ~/.nvm/nvm.sh
  elif command -v brew; then
    _brew_prefix=$(brew --prefix nvm)
    if [ -f "$_brew_prefix/nvm.sh" ]; then
      echo "Sourcing nvm from brew ($_brew_prefix)"
      . "$_brew_prefix"/nvm.sh
    fi
  else
    echo "Please make sure nvm is installed (correctly), please follow the installation instructions
              at: https://github.com/nvm-sh/nvm  
            "
  fi
}

source_nvm
# automatically change node version to the one indicated in .nvmrc
nvm use

# Check if package-lock.json changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet 'package-lock.json'; then
  echo "📦 package-lock.json changed, running npm install..."
  npm install --prefer-offline --no-audit
fi

# Check if OpenAPI files changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet 'src/openapi/'; then
  echo "🔧 OpenAPI files changed, rebuilding models..."
  npm run build:models
fi
