#!/bin/sh

# Check if package-lock.json changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet 'package-lock.json'; then
  echo "📦 package-lock.json changed, running npm install..."
  npm install --prefer-offline --no-audit
fi

# Check if OpenAPI files changed
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet 'src/openapi/'; then
  echo "🔧 OpenAPI files changed, rebuilding models..."
  npm run build:models
fi
