name: Renovate
on:
  schedule:
    - cron: '0/30 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Renovate
        uses: renovatebot/github-action@v26.21.7
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.NPM_TOKEN }}
