AppList:
  type: string
  # uniqueItems: true
  # items:
  #   type: string
  enum:
    - alertmanager
    - argocd
    - cert-manager
    - cnpg
    - external-dns
    - gitea
    - grafana
    - harbor
    - ingress-nginx
    - istio
    - keycloak
    - knative
    - kserve
    - kubeflow-pipelines
    - kyverno
    - loki
    - minio
    - otel
    - prometheus
    - rabbitmq
    - tekton
    - thanos
    - sealed-secrets
    - tempo
    - trivy

App:
  x-acl:
    platformAdmin: [read-any, update-any]
    teamAdmin: [read, update]
    teamMember: [read, update]
  type: object
  properties:
    enabled:
      type: boolean
    id:
      $ref: 'definitions.yaml#/idName'
      x-acl:
        platformAdmin: [read-any]
        teamAdmin: [read-any]
        teamMember: [read-any]
      # readOnly: true
    rawValues:
      $ref: 'definitions.yaml#/rawValues'
      x-acl:
        platformAdmin: [read-any, update-any]
        teamAdmin: []
        teamMember: []
    values:
      x-acl:
        platformAdmin: [read-any, update-any]
        teamAdmin: []
        teamMember: []
      type: object
      additionalProperties: true
  required: [id]

AppEnabled:
  x-acl:
    platformAdmin: [read-any]
    teamAdmin: [read-any]
    teamMember: [read-any]
  type: object
  properties:
    id:
      $ref: 'definitions.yaml#/idName'
    enabled:
      type: boolean
