AppList:
  type: string
  # uniqueItems: true
  # items:
  #   type: string
  enum:
    - alertmanager
    - argocd
    - cert-manager
    - cnpg
    - drone
    - external-dns
    - falco
    - gitea
    - grafana
    - harbor
    - httpbin
    - ingress-nginx
    - istio
    - jaeger
    - keycloak
    - kiali
    - knative
    - kured
    - kyverno
    - loki
    - minio
    - otel
    - prometheus
    - rabbitmq
    - tekton
    - sealed-secrets
    - tempo
    - trivy
    - velero

App:
  x-acl:
    admin: [read-any, update-any]
    team: [read, update]
  type: object
  properties:
    enabled:
      type: boolean
    id:
      $ref: definitions.yaml#/idName
      x-acl:
        admin: [read-any]
        team: [read-any]
      # readOnly: true
    rawValues:
      $ref: definitions.yaml#/rawValues
      x-acl:
        admin: [read-any, update-any]
        team: []
    values:
      x-acl:
        admin: [read-any, update-any]
        team: []
      type: object
  required: [id]
