AppList:
  type: string
  # uniqueItems: true
  # items:
  #   type: string
  enum:
    - alertmanager
    - argocd
    - cert-manager
    - cnpg
    - drone
    - external-dns
    - falco
    - gitea
    - grafana
    - harbor
    - httpbin
    - ingress-nginx
    - istio
    - jaeger
    - keycloak
    - kiali
    - knative
    - kured
    - kyverno
    - loki
    - minio
    - otel
    - prometheus
    - rabbitmq
    - tekton
    - sealed-secrets
    - tempo
    - trivy
    - velero

# AppBase:
#   x-acl:
#     admin: [read-any, update-any]
#     team: [read, update]
#   type: object
#   properties:
#     id:
#       $ref: definitions.yaml#/idName
#     rawValues:
#       $ref: definitions.yaml#/rawValues
#     shortcuts:
#       description: Resource URL that lands the user in a place of interest within an app.
#       type: array
#       nullable: true
#       items:
#         $ref: definitions.yaml#/shortcut

App:
  x-acl:
    admin: [read-any, update-any]
    team: [read, update]
  type: object
  properties:
    enabled:
      type: boolean
    id:
      $ref: definitions.yaml#/idName
      x-acl:
        admin: [read-any]
        team: [read-any]
      # readOnly: true
    rawValues:
      $ref: definitions.yaml#/rawValues
      x-acl:
        admin: [read-any, update-any]
        team: []
    shortcuts:
      description: Resource URL that lands the user in a place of interest within an app.
      type: array
      items:
        $ref: definitions.yaml#/shortcut
      x-acl:
        admin: [read-any, update-any]
        team: []
    values:
      x-acl:
        admin: [read-any, update-any]
        team: []
      type: object
  required: [id]
