Build:
  x-acl:
    admin:
      - delete-any
      - read-any
      - create-any
      - update-any
    team:
      - delete
      - read
      - create
      - update
  type: object
  x-externalDocsPath: docs/console/builds
  properties:
    id:
      type: string
    teamId:
      $ref: 'definitions.yaml#/idName'
    name:
      title: Build name
      $ref: 'definitions.yaml#/wordCharacterPattern'
      description: Results in image name harbor.example.com/<team-name>/name
    tag:
      $ref: 'definitions.yaml#/imageTag'
      default: v0.0.1
    mode:
      title: Mode
      description: Choose between Docker or Buildpacks
      type: object
      oneOf:
        - title: Docker
          type: object
          description: Build from source using a Dockerfile
          properties:
            docker:
              additionalProperties: false
              type: object
              x-hideTitle: true
              properties:
                repoUrl:
                  description: The URL of the Git repo that contains the application code.
                  $ref: 'definitions.yaml#/url'
                path:
                  description: The path to the Dockerfile to execute (defaults to ./Dockerfile)
                  type: string
                revision:
                  description: This can be commit, tag, or branch. If omitted, will equal to HEAD.
                  $ref: 'definitions.yaml#/wordCharacterPattern'
                  default: HEAD
              required:
                - repoUrl
            type:
              type: string
              enum:
                - docker
              default: docker
          required:
            - docker
            - type
        - title: Buildpacks
          type: object
          description: Build from source using Buildpacks
          properties:
            buildpacks:
              additionalProperties: false
              x-hideTitle: true
              type: object
              properties:
                repoUrl:
                  description: The URL of the Git repo that contains the application code.
                  $ref: 'definitions.yaml#/url'
                path:
                  description: A subpath within the source input where the source to build is located (optional)
                  type: string
                  default: ""
                revision:
                  description: This can be commit, tag, or branch. If omitted, will equal to HEAD.
                  $ref: 'definitions.yaml#/wordCharacterPattern'
                  default: HEAD
              required:
                - repoUrl
            type:
              type: string
              enum:
                - buildpacks
              default: buildpacks
          required:
            - buildpacks
            - type
    repoAccess:
      title: Repository access (Optional)
      description: Configure access to private repositories.
      properties:
        otomiGit:
          title: Otomi Gitea repo?
          description: Set to true when using a Otomi Gitea repo and let Otomi configure access.
          type: boolean
          default: false
        privateGit:
          title: Private repo?
          description: Set to true when using a private repo and fill in the username and password.
          type: boolean
          default: false
        repoUserName:
          title: user name
          description: The username used to access a private git repo.
          $ref: 'definitions.yaml#/wordCharacterPattern'
        repoPassword:
          x-secret: ''
          title: password
          $ref: 'definitions.yaml#/wordCharacterPattern'
          description: The password used to access a private github repo.

  required:
    - name
