Build:
  x-acl:
    admin:
      - delete-any
      - read-any
      - create-any
      - update-any
    team:
      - delete
      - read
      - create
      - update
  type: object
  description: Define location of the application code for build
  properties:
    id:
      type: string
    teamId:
      $ref: 'definitions.yaml#/idName'
    name:
      title: Build name
      $ref: 'definitions.yaml#/wordCharacterPattern'
      description: Results in registry harbor.<domain>/<team-name>/name
    tag:
      $ref: 'definitions.yaml#/imageTag'
      default: v0.0.1
    repoUrl:
      description: The URL of the Git repo that contains the application code.
      $ref: 'definitions.yaml#/url'
    path:
      description: A relative directory path within the Git repository.
      $ref: 'definitions.yaml#/wordCharacterPattern'
    revision:
      description: This can be commit, tag, or branch. If omitted, will equal to HEAD.
      $ref: 'definitions.yaml#/wordCharacterPattern'
      default: HEAD
    otomiGit:
      title: Otomi Gitea repo?
      description: Set to true when using a Otomi Gitea repo and let Otomi configure access.
      type: boolean
      default: false
    privateGit:
      title: Private repo?
      description: Set to true when using a private repo and fill in the username and password.
      type: boolean
      default: false
    repoUserName:
      title: user name
      description: The username used to access a private git repo.
      $ref: 'definitions.yaml#/wordCharacterPattern'
    repoPassword:
      x-secret: ''
      title: password
      $ref: 'definitions.yaml#/wordCharacterPattern'
      description: The password used to access a private github repo.

  required:
    - name
    - repoUrl
