Build:
  x-acl:
    admin:
      - delete-any
      - read-any
      - create-any
      - update-any
    team:
      - delete
      - read
      - create
      - update
  type: object
  x-externalDocsPath: docs/for-devs/console/builds
  properties:
    id:
      type: string
    teamId:
      $ref: 'definitions.yaml#/idName'
    name:
      title: Build name
      $ref: 'definitions.yaml#/wordCharacterPattern'
      description: Results in image name harbor.<your-domain>/<team-name>/name
    tag:
      $ref: 'definitions.yaml#/imageTag'
      default: latest
      description: Image tag
    mode:
      $ref: '#/buildMode'
    repoAccess:
      title: Repository access (Optional)
      description: Configure access to private repositories.
      properties:
        otomiGit:
          title: Otomi Gitea repo?
          description: Set to true when using a Otomi Gitea repo
          type: boolean
          default: false
        privateGit:
          title: Private repo?
          description: Set to true when using a private repo and fill in the username and password
          type: boolean
          default: false
        repoUserName:
          title: user name
          description: The username used to access a private git repo
          $ref: 'definitions.yaml#/wordCharacterPattern'
        repoPassword:
          x-secret: true
          title: password
          $ref: 'definitions.yaml#/wordCharacterPattern'
          description: The password used to access a private github repo
  required:
    - name

buildMode:
  title: Mode
  description: Choose between Docker or Buildpacks
  type: object
  default: 1
  oneOf:
    - title: Docker
      type: object
      x-hideTitle: true
      description: Build from source using a Dockerfile
      properties:
        docker:
          additionalProperties: false
          type: object
          title: Docker
          properties:
            repoUrl:
              description: The URL of the Git repo that contains the application code
              $ref: 'definitions.yaml#/url'
              title: Repo URL
            path:
              description: The path to the Dockerfile to execute (defaults to ./Dockerfile)
              type: string
              default: ./Dockerfile
            revision:
              description: This can be a commit, a tag, or a branch
              $ref: 'definitions.yaml#/wordCharacterPattern'
              default: HEAD
          required:
            - repoUrl
        type:
          type: string
          enum:
            - docker
          default: docker
      required:
        - docker
        - type
    - title: Buildpacks
      type: object
      x-hideTitle: true
      description: Build from source using Buildpacks
      properties:
        buildpacks:
          additionalProperties: false
          type: object
          properties:
            repoUrl:
              description: The URL of the Git repo that contains the application code
              $ref: 'definitions.yaml#/url'
              title: Repo URL
            path:
              description: A subpath within the repo where the source to build is located (optional)
              type: string
              default: ''
            revision:
              description: This can be a commit, a tag, or a branch
              $ref: 'definitions.yaml#/wordCharacterPattern'
              default: HEAD
          required:
            - repoUrl
        type:
          type: string
          enum:
            - buildpacks
          default: buildpacks
      required:
        - buildpacks
        - type
