Build:
  x-acl:
    admin:
      - delete-any
      - read-any
      - create-any
      - update-any
    team:
      - delete
      - read
      - create
      - update
  type: object
  x-externalDocsPath: docs/for-devs/console/builds
  properties:
    id:
      type: string
    teamId:
      $ref: 'definitions.yaml#/idName'
    name:
      title: Build name
      $ref: 'definitions.yaml#/wordCharacterPattern'
      description: Results in image name harbor.<your-domain>/<team-name>/name
    tag:
      $ref: 'definitions.yaml#/imageTag'
      default: latest
      description: Image tag
    mode:
      $ref: '#/buildMode'
    externalRepo:
      type: boolean
      description: Select when using an external private Git repository
      default: false
    secretName:
      description: The name of the secret with the credentials of the external private Git repository
      type: string
    trigger:
      type: boolean
      default: false
      description: "Trigger the build based on a Gitea webhook. Use this URL for the webhook: http://el-gitea-webhook-<build-name>.team-<team-name>.svc.cluster.local:8080"
    scanSource:
      type: boolean
      default: true
      description: Select to scan source code
  required:
    - name

buildMode:
  title: Mode
  description: Choose between Docker or Buildpacks
  type: object
  oneOf:
    - title: Docker
      type: object
      x-hideTitle: true
      description: Build from source using a Dockerfile
      properties:
        docker:
          additionalProperties: false
          type: object
          title: Docker
          properties:
            repoUrl:
              description: The URL of the Git repo that contains the application code
              $ref: 'definitions.yaml#/url'
              title: Repo URL
            path:
              description: The path to the Dockerfile to execute (defaults to ./Dockerfile)
              type: string
              default: ./Dockerfile
            revision:
              description: This can be a commit, a tag, or a branch
              $ref: 'definitions.yaml#/wordCharacterPattern'
              default: HEAD
            envVars:
              title: Environment variables
              type: array
              items:
                type: object
                description: Environment variable to set during build-time
                properties:
                  name:
                    title: Name
                    type: string
                  value:
                    title: Value
                    type: string
                required:
                  - name
                  - value
          required:
            - repoUrl
        type:
          type: string
          enum:
            - docker
          default: docker
      required:
        - docker
        - type
    - title: Buildpacks
      type: object
      x-hideTitle: true
      description: Build from source using Buildpacks
      properties:
        buildpacks:
          additionalProperties: false
          type: object
          properties:
            repoUrl:
              description: The URL of the Git repo that contains the application code
              $ref: 'definitions.yaml#/url'
              title: Repo URL
            path:
              description: A subpath within the repo where the source to build is located (optional)
              type: string
              default: ''
            revision:
              description: This can be a commit, a tag, or a branch
              $ref: 'definitions.yaml#/wordCharacterPattern'
              default: HEAD
            envVars:
              title: Environment variables
              type: array
              items:
                type: object
                description: Environment variable to set during build-time
                properties:
                  name:
                    title: Name
                    type: string
                  value:
                    title: Value
                    type: string
                required:
                  - name
                  - value
          required:
            - repoUrl
        type:
          type: string
          enum:
            - buildpacks
          default: buildpacks
      required:
        - buildpacks
        - type
