Deployment:
  x-externalDocsPath: docs/console/deploy-changes
  x-acl:
    admin: [read-any]
    team: [read-any]
  properties:
    id:
      type: string
    status:
      type: string
      readOnly: true
      description: Deployment status
      enum:
        - in-progress
        - completed
        - failed
  type: object
