Deployment:
  x-externalDocsPath: 'docs/deployment'
  x-acl:
    admin: [read-any]
    team: [read-any]
  properties:
    id:
      type: integer
    status:
      type: string
      readOnly: true
      description: Deployment status
      enum:
        - in-progress
        - completed
        - failed
