Project:
  x-acl:
    platformAdmin:
      - create-any
      - read-any
      - update-any
      - delete-any
    teamAdmin:
      - create
      - read
      - update
      - delete
    teamMember:
      - create
      - read
      - update
      - delete
  type: object
  x-externalDocsPath: docs/for-devs/console/projects
  properties:
    id:
      type: string
    teamId:
      $ref: 'definitions.yaml#/idName'
    name:
      title: Project name
      $ref: 'definitions.yaml#/idName'
    build:
      $ref: 'build.yaml#/Build'
    workload:
      $ref: 'workload.yaml#/Workload'
    workloadValues:
      $ref: 'workload.yaml#/WorkloadValues'
    service:
      $ref: 'service.yaml#/Service'
  required:
    - name
