Service:
  x-acl:
    admin:
      - delete-any
      - read-any
      - create-any
      - update-any
    team:
      - delete
      - read-any
      - create
      - update
  x-externalDocsPath: docs/configuring-services
  properties:
    enabled:
      default: true
      type: boolean
    id:
      readOnly: true
      type: string
    name:
      $ref: definitions.yaml#/idName
      title: Name
      description: A service name
      example: some-service
    port:
      description: A service port
      type: integer
      default: 80
      minimum: 1
      maximum: 65535
    ksvc:
      oneOf:
        - $ref: definitions.yaml#/svcPredeployed
        - $ref: definitions.yaml#/ksvcPredeployed
        - $ref: definitions.yaml#/ksvcNew
      title: Type
    ingress:
      nullable: true
      title: Exposure (ingress)
      # Note: the order matters first schema must be nullable empty object
      oneOf:
        - $ref: api.yaml#/components/schemas/ingressCluster
        - $ref: api.yaml#/components/schemas/ingressPrivate
        - $ref: api.yaml#/components/schemas/ingressPublic
        - $ref: api.yaml#/components/schemas/ingressTls

    teamId:
      $ref: definitions.yaml#/idName
      readOnly: true
  required:
    - name
    - ingress
  type: object
