domain: &domainNameField
  type: string
  pattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
repository: &repositoryField
  type: string
  pattern: ^[a-z0-9]+(?:[/._-]{1,2}[a-z0-9]+)*$
  description: A container image repository
memoryQuantity: &k8sResourceMemoryQuantityField
  type: string
  pattern: ^[0-9]+\.?[0-9]+(E|P|T|G|M|K|Ei|Pi|Ti|Gi|Mi|Ki)?$
cpuQuantity: &k8sResourceCpuQuantityField
  type: string
  pattern: ^([0-9]+\.[0-9]{1,2})|([0-9]{2,3}m)?$
env: &envField
  type: string
  pattern: ^[a-zA-Z0-9_]*$
annotation: &k8sAnnotationField
  type: string
  pattern: ^((.){1,253}\/)?(.){1,63}$
idName: &idNameField
  type: string
  pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$

x-annotations: &K8sAnnotation
  description: Kubernetes annotations with arbitrary metadata
  type: array
  items:
    type: object
    properties:
      name:
        <<: *k8sAnnotationField
      value:
        type: string
        maxLength: 32767

ServiceIngress:
  properties: &ServiceIngress
    useDefaultSubdomain:
      title: 'Use team domain (preferred)'
      type: boolean
      default: true
      description: Use the team domain so that the URL reveals the owner.
    subdomain:
      title: 'Host'
      type: string
      nullable: true
      description: A host that is used to set DNS 'A' records
      <<: *domainNameField
    domain:
      title: DNS Zone
      description: A managed DNS zone
      type: string
    path:
      title: URL path
      description: The path in the URL that the service should be mapped to (e.g. for microservices on one app/domain.)
      type: string
    forwardPath:
      title: Forward path
      description: Forward the URL path into the service (don't rewrite to /)
      type: boolean
    hasSingleSignOn:
      title: Authenticate with Single Sign On
      type: boolean
      default: false
    hasCert:
      title: Already has a certificate
      type: boolean
      default: false
      description: If true a certificate should exist already
    certArn:
      type: string
      title: Certificate ARN
      example: arn:aws:acm:eu-central-1:xxx:certificate/xxx
    certSelect:
      type: boolean
      title: Select existing secret name
      default: true
    certName:
      type: string
      title: Secret name
      example: www-example-com
  required:
    - domain
    - subdomain

Service:
  x-externalDocsPath: 'otomi/docs/configuring-services'
  x-acl:
    admin: [delete-any, read-any, create-any, update-any]
    team: [delete, read, create, update]
  type: object
  properties:
    id:
      type: string
      readOnly: true
    name:
      <<: *idNameField
      title: Name
      description: A service name
      example: some-service
    clusterId:
      title: Cluster ID
      type: string
      description: A kubernetes cluster for the service
      x-acl:
        admin: [read, create]
        team: [read, create]
    port:
      title: Service port
      type: integer
      default: 80
      minimum: 1
      maximum: 65535
    ingress:
      title: Exposure
      type: object
      x-acl:
        team: [read]
      oneOf:
        - title: Private
          nullable: true
          additionalProperties: false
        - title: Public URL
          nullable: true
          properties:
            <<: *ServiceIngress
    ksvc:
      title: Type
      type: object
      oneOf:
        - title: Knative service
          nullable: true
          properties:
            serviceType:
              type: string
              enum: [ksvc]
              default: ksvc
            scaleToZero:
              title: Scale to zero
              description: Scales to zero after 60 seconds and needs approximately 8 seconds to start back up.
              type: boolean
              default: false
            image:
              title: Container image
              type: object
              nullable: true
              properties:
                repository:
                  <<: *repositoryField
                tag:
                  type: string
            secrets:
              type: array
              title: Secrets
              nullable: true
              items:
                type: object
                properties:
                  name:
                    type: string
                  entries:
                    title: Entries
                    type: array
                    items:
                      type: string
                    uniqueItems: true
                required:
                  - name
              required:
                - repository
                - tag
            env:
              title: Environment variables
              # description: Environment variables for containers
              type: array
              nullable: true
              items:
                type: object
                properties:
                  name:
                    <<: *envField
                  value:
                    type: string
                    maxLength: 131072
                required:
                  - name
                  - value
            resources:
              title: Pod resources
              # description: Compute resources for containers
              type: object
              nullable: true
              properties:
                requests:
                  type: object
                  properties:
                    cpu:
                      description: 'The guaranteed amount of CPU'
                      <<: *k8sResourceCpuQuantityField
                      default: 50m
                    memory:
                      description: 'The guaranteed amount of RAM'
                      <<: *k8sResourceMemoryQuantityField
                      default: 64Mi
                  required:
                    - cpu
                    - memory
                limits:
                  type: object
                  properties:
                    cpu:
                      description: 'The maximal amount of CPU'
                      <<: *k8sResourceCpuQuantityField
                      default: 100m
                    memory:
                      description: 'The maximal amount of RAM'
                      <<: *k8sResourceMemoryQuantityField
                      default: 128Mi
                  required:
                    - cpu
                    - memory
            annotations:
              title: Pod annotations
              <<: *K8sAnnotation
            autoCD:
              title: Continuous delivery pipeline
              description: Deploys new images based on a tagging strategy
              type: object
              oneOf:
                - title: 'Off'
                  nullable: true
                  additionalProperties: false
                - title: Semver versioning
                  nullable: true
                  properties:
                    tagMatcher:
                      type: string
                      enum: [semver]
                      default: semver
                    semver:
                      title: Semver version pattern
                      type: string
                      example: 'PATCH only: "~1.1", MINOR and PATCH only "~1", ALL "*",  ">=1.2.3-0"'
                      description:
                        'Use this filter if your images tags follow semantic versioning rules (MAJOR.MINOR.PATCH). E.g.:
                        PATCH only: "~1.1", MINOR and PATCH only "~1", ALL "*"'
                  required:
                    - semver
                  # additionalProperties: false
                - title: Glob pattern matching
                  # nullable: true
                  properties:
                    tagMatcher:
                      type: string
                      enum: [glob]
                      default: glob
                    glob:
                      title: Glob string pattern
                      type: string
                      description: 'Use this filter if you want to make simple non-standard patterns. E.g.: "master-v1.*.*"'
                      example: 'master-v1.*.*'
                  required:
                    - glob
                  additionalProperties: false
        - title: Existing Knative service
          properties:
            serviceType:
              type: string
              enum: [ksvcPredeployed]
              default: ksvcPredeployed
          required:
            - serviceType
        - title: Existing Kubernetes service
          properties:
            serviceType:
              type: string
              enum: [svcPredeployed]
              default: svcPredeployed
          required:
            - serviceType
    teamId:
      type: string
      readOnly: true
  required:
    - name
    - clusterId
