Service:
  x-acl:
    admin:
      - delete-any
      - read-any
      - create-any
      - update-any
    team:
      - delete
      - read-any
      - create
      - update
  x-externalDocsPath: docs/configuring-services
  properties:
    enabled:
      default: true
      type: boolean
    id:
      readOnly: true
      type: string
    name:
      $ref: definitions.yaml#/idName
      title: Name
      description: A kubernetes service name.
      example: some-service
    port:
      description: A service port
      type: integer
      default: 80
      minimum: 1
      maximum: 65535
    ksvc:
      oneOf:
        - $ref: definitions.yaml#/svcPredeployed
        - $ref: definitions.yaml#/ksvcPredeployed
        - $ref: definitions.yaml#/ksvcNew
      title: Service type
      description: Type of service. Can be a knative service or a regular service.
      x-externalDocsPath: https://otomi.io/docs/console/configuring-services/#type
    ingress:
      # nullable: true
      title: Exposure (ingress)
      description: Determines loadbalancer related configuration for handling the service ingress.
      # Note: the order matters first schema must be nullable empty object
      oneOf:
        - $ref: definitions.yaml#/ingressCluster
        - $ref: definitions.yaml#/ingressPrivate
        - $ref: definitions.yaml#/ingressPublic
      x-externalDocsPath: https://otomi.io/docs/console/configuring-services/#exposure
    teamId:
      $ref: definitions.yaml#/idName
      readOnly: true
  required:
    - name
    - ingress
  type: object
