Service:
  x-externalDocsPath: 'docs/configuring-services'
  x-acl:
    admin: [delete-any, read-any, create-any, update-any]
    team: [delete, read, create, update]
  properties:
    enabled:
      type: boolean
      default: true
    id:
      type: string
      readOnly: true
    name:
      $ref: definitions.yaml#/idName
      title: Name
      description: A service name
      example: some-service
    port:
      description: A service port
      type: integer
      default: 80
      minimum: 1
      maximum: 65535
    clusterId:
      title: Cluster ID
      type: string
      description: A kubernetes cluster for the service
      x-acl:
        admin: [read, create]
        team: [read, create]
    ksvc:
      title: Type
      oneOf:
        - title: Knative service
          nullable: true
          properties:
            serviceType:
              type: string
              enum: [ksvc]
              default: ksvc
            scaleToZero:
              title: Scale to zero
              description: Scales to zero after 60 seconds and needs approximately 8 seconds to start back up.
              type: boolean
              default: false
            image:
              title: Container image
              nullable: true
              properties:
                repository:
                  $ref: definitions.yaml#/repository
                tag:
                  type: string
            secrets:
              type: array
              items:
                properties:
                  name:
                    type: string
                  entries:
                    title: Entries
                    type: array
                    items:
                      type: string
                    uniqueItems: true
                required:
                  - name
              required:
                - repository
                - tag
            env:
              title: Environment variables
              # description: Environment variables for containers
              type: array
              nullable: true
              items:
                properties:
                  name:
                    $ref: definitions.yaml#/env
                  value:
                    type: string
                    maxLength: 131072
                required:
                  - name
                  - value
            resources:
              title: Pod resources
              # description: Compute resources for containers
              nullable: true
              properties:
                requests:
                  properties:
                    cpu:
                      description: The guaranteed amount of CPU
                      $ref: definitions.yaml#/cpuQuantity
                      default: 50m
                    memory:
                      description: The guaranteed amount of RAM
                      $ref: definitions.yaml#/memoryQuantity
                      default: 64Mi
                  required:
                    - cpu
                    - memory
                limits:
                  properties:
                    cpu:
                      description: The maximum amount of CPU
                      $ref: definitions.yaml#/cpuQuantity
                      default: 100m
                    memory:
                      description: The maximum amount of RAM
                      $ref: definitions.yaml#/memoryQuantity
                      default: 128Mi
                  required:
                    - cpu
                    - memory
            annotations:
              title: Pod annotations
              $ref: definitions.yaml#/annotations
            autoCD:
              title: Continuous delivery
              description: Deploys new images based on a tagging strategy
              oneOf:
                - title: 'Off'
                  nullable: true
                  additionalProperties: false
                - title: Semver versioning
                  nullable: true
                  properties:
                    tagMatcher:
                      type: string
                      enum: [semver]
                      default: semver
                    semver:
                      title: Semver version pattern
                      type: string
                      example: 'PATCH only: "~1.1", MINOR and PATCH only "~1", ALL "*",  ">=1.2.3-0"'
                      description:
                        'Use this filter if your image tags follow semantic versioning rules (MAJOR.MINOR.PATCH). E.g.:
                        PATCH only: "~1.1", MINOR and PATCH only "~1", ALL "*"'
                  required:
                    - semver
                  # additionalProperties: false
                - title: Glob pattern matching
                  # nullable: true
                  properties:
                    tagMatcher:
                      type: string
                      enum: [glob]
                      default: glob
                    glob:
                      title: Glob string pattern
                      type: string
                      description: 'Use this filter if you want to make glob-style patterns. E.g.: "main-v1.3.*"'
                      example: 'main-v1.3.*'
                  required:
                    - glob
                  additionalProperties: false
        - title: Existing Knative service
          properties:
            serviceType:
              type: string
              enum: [ksvcPredeployed]
              default: ksvcPredeployed
          required:
            - serviceType
        - title: Existing Kubernetes service
          properties:
            serviceType:
              type: string
              enum: [svcPredeployed]
              default: svcPredeployed
          required:
            - serviceType
    ingress:
      title: Exposure
      x-acl:
        team: [read]
      oneOf:
        - title: Private
          nullable: true
          additionalProperties: false
        - title: Public URL
          nullable: true
          properties:
            useDefaultSubdomain:
              title: Use team domain (preferred)
              type: boolean
              default: true
              description: Use the team domain so that the URL reveals the owner.
            subdomain:
              title: 'Host'
              type: string
              nullable: true
              description: A host that is used to set DNS 'A' records
              $ref: definitions.yaml#/domain
            domain:
              title: DNS Zone
              description: A managed DNS zone
              type: string
            path:
              title: URL path
              description: The path in the URL that the service should be mapped to (e.g. for microservices on one app/domain.)
              type: string
            forwardPath:
              title: Forward path
              description: Forward the URL path into the service (don't rewrite to /)
              type: boolean
            hasSingleSignOn:
              title: Authenticate with Single Sign On
              type: boolean
              default: false
            hasCert:
              title: Already has a certificate
              type: boolean
              default: false
              description: If true a certificate should exist already
            certArn:
              type: string
              title: Certificate ARN
              example: arn:aws:acm:eu-central-1:xxx:certificate/xxx
            certSelect:
              type: boolean
              title: Select existing secret name
              default: true
            certName:
              type: string
              title: Secret name
              example: www-example-com
          required:
            - domain
            - subdomain
    teamId:
      type: string
      readOnly: true
  required:
    - name
    - clusterId
    - teamId
