Service:
  x-acl:
    platformAdmin:
      - create-any
      - read-any
      - update-any
      - delete-any
    teamAdmin:
      - create
      - read
      - update
      - delete
    teamMember:
      - create
      - read
      - update
      - delete
  x-externalDocsPath: docs/for-devs/console/services
  properties:
    id:
      # readOnly: true
      type: string
    teamId:
      $ref: definitions.yaml#/idName
      # readOnly: true
    name:
      title: Name
      $ref: definitions.yaml#/idName
      example: some-service
      x-formtype: SelectWidget
    namespace:
      $ref: definitions.yaml#/idName
      description: A Kubernetes namespace.
      x-acl:
        platformAdmin:
          - create-any
          - read-any
          - update-any
          - delete-any
        teamAdmin: []
        teamMember: []
    port:
      type: integer
      minimum: 1
      maximum: 65535
      default: 80
      x-formtype: SelectWidget
    ksvc:
      type: object
      properties:
        predeployed:
          description: Set this flag it the service is managed by Knative service.
          type: boolean
          default: false
      # x-hidden: true
    trafficControl:
      title: Traffic Control
      description: Split traffic between multiple versions (blue-green, canary).
      properties:
        enabled:
          type: boolean
          default: false
        weightV1:
          type: integer
          default: 90
          title: Weight v1
          description: 'Percentage of traffic to version 1.'
        weightV2:
          type: integer
          default: 10
          title: Weight v2
          description: 'Percentage of traffic to version 2.'
    ingress:
      title: Exposure (ingress)
      description: Determines loadbalancer related configuration for handling the service ingress.
      $ref: '#/Ingress'
      # Note: the order matters first schema must be nullable empty object

  required:
    - name
    - ingress

Ingress:
  properties:
    ingressClassName:
      description: Assign service to a paricular Load Balancer by selecting ingress class name.
      title: Ingress Class Name
      $ref: 'definitions.yaml#/idName'
      default: 'platform'
    tlsPass:
      description: Pass through the request as is to the backing service. Only available for pre-deployed regular (non-Knative) services.
      title: TLS passthrough
      type: boolean
      default: false
    useDefaultHost:
      description: Use the team domain so that the URL reveals the owner.
      title: Use default host
      type: boolean
      default: true
    subdomain:
      $ref: definitions.yaml#/domain
      description: A host that is used to set DNS 'A' records.
      title: Host
      type: string
    domain:
      $ref: definitions.yaml#/domain
      description: A managed DNS zone
      title: DNS Zone
      type: string
    useCname:
      title: Use CNAME
      description: Define a CNAME for the service.
      type: boolean
      default: false
    cname:
      properties:
        domain:
          description: A domain name (an alias).
          type: string
        tlsSecretName:
          description: Name of a Kubernetes secret of type TLS.
          $ref: 'definitions.yaml#/idName'
    paths:
      description: The paths in the URL that the service should be mapped to (e.g. for microservices on one app/domain).
      title: URL paths
      type: array
      items:
        $ref: definitions.yaml#/path
    forwardPath:
      description: Forward the URL path into the service (don't rewrite to /).
      title: Forward path
      type: boolean
      default: false
    hasCert:
      description: Select when a certificate exists and should not be generated.
      title: Already has a certificate
      type: boolean
      default: false
    certSelect:
      description: Select a TLS SealedSecret.
      title: Select team secret
      type: boolean
      default: true
    certName:
      description: The name of a TLS secret known to exist in the Team namespace.
      example: example-com
      title: Secret name
      type: string
    headers:
      additionalProperties: false
      type: object
      properties:
        response:
          type: object
          title: HTTP Response Headers
          description: The following HTTP response headers will be set. Adjust, remove or add more if needed.
          properties:
            set:
              type: array
              items:
                type: object
                properties:
                  name:
                    title: Name
                    type: string
                  value:
                    title: Value
                    type: string
                required:
                  - name
                  - value

IngressCluster:
  additionalProperties: false
  title: No Exposure
  type: object
  nullable: true
  properties:
    type:
      type: string
      enum:
        - cluster
      default: cluster

IngressPublic:
  allOf:
    - $ref: '#/Ingress'
    - properties:
        type:
          type: string
          enum:
            - public
          default: public
  nullable: true
  description: Will only accept traffic coming from an external loadbalancer.
  title: External
